server:
  port: 8097

spring:
  application:
    name: client-aim-server
  security:
    oauth2:
      client:
        registration:
          bar-auth: #unique supplier service name
            client-id: macros-gateway-client
            client-secret: KgHWIcm429s1Z59x9U6C39tcFlLWBlP5
            authorization-grant-type: client_credentials
            client-authentication-method: post
        provider:
          bar-auth:
            token-uri: ${BAR_AUTH_SERVER_URI}/oauth/token
      resourceserver:
        opaquetoken:
          client-id: macros-gateway-client
          client-secret: KgHWIcm429s1Z59x9U6C39tcFlLWBlP5
          introspection-uri: http://localhost:8070/realms/macros-realm/protocol/openid-connect/token/introspect
        jwt:
          jwk-set-uri: http://localhost:8070/realms/macros-realm/protocol/openid-connect/certs

eureka:
  client:
    server-url:
      default-zone: http://localhost:8761/eureka

logstash:
  host: localhost
