server:
  port: 8097

spring:
  application:
    name: client-aim-server
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: macros-gateway-client
          client-secret: KgHWIcm429s1Z59x9U6C39tcFlLWBlP5
          introspection-uri: http://localhost:8070/realms/macros-realm/protocol/openid-connect/token/introspect
        jwt:
          jwk-set-uri: http://localhost:8070/realms/macros-realm/protocol/openid-connect/certs

eureka:
  client:
    server-url:
      default-zone: http://localhost:8761/eureka

logstash:
  host: localhost
