server:
  port: 8098

eureka:
  client:
    server-url:
      default-zone: http://localhost:8761/eureka

logstash:
  host: localhost

spring:
  application:
    name: daily-diet-server
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: macros-gateway-client
          client-secret: GA2GS6zMfYHoYltpOSoOMcgQpBCiaAVo
          introspection-uri: http://localhost:8070/realms/macros-realm/protocol/openid-connect/token/introspect
        jwt:
          jwk-set-uri: http://localhost:8070/realms/macros-realm/protocol/openid-connect/certs
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: password
      database: daily-diet-db
      port: 27017
      host: localhost
      auto-index-creation: true
