server:
  port: 8095

spring:
  application:
    name: dish-macros-calculation-server

eureka:
  client:
    server-url:
      default-zone: http://localhost:8761/eureka

logstash:
  host: localhost

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
