server:
  port: 8092

eureka:
  client:
    server-url:
      default-zone: http://localhost:8761/eureka

logstash:
  host: localhost

spring:
  application:
    name: food-read-server
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: macros-gateway-client
          client-secret: KgHWIcm429s1Z59x9U6C39tcFlLWBlP5
          introspection-uri: http://localhost:8070/realms/macros-realm/protocol/openid-connect/token/introspect
        jwt:
          jwk-set-uri: http://localhost:8070/realms/macros-realm/protocol/openid-connect/certs
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: password
      database: food-slave-db
      port: 27017
      host: localhost
      auto-index-creation: true
  cloud:
    function:
      definition: consumer
    stream:
      bindings:
        consumer-in-0:
          destination: food-write-operation
      binder:
        brokers: localhost:9092