server:
  port: 8086
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
zuul:
  ignoredServices: '*'
  routes:
    customer:
      path: /customer/**
      serviceId: customer
    fraud:
      path: /fraud/**
      serviceId: fraud
    
  
