server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: dish-macros-calculation-server
          uri: lb://DISH-MACROS-CALCULATION-SERVER
          predicates:
            - Path=/calculate-dish/**
        - id: dish-server
          uri: lb://DISH-SERVER
          predicates:
            - Path=/dish/**
        - id: user-server
          uri: lb://USER-SERVER
          predicates:
            - Path=/users/**
        - id: person-macros-calculation-server
          uri: lb://PERSON-MACROS-CALCULATION-SERVER
          predicates:
            - Path=/calculate-person/**
        - id: food-server
          uri: lb://FOOD-SERVER
          predicates:
            - Path=/food/**
