server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8070/realms/macros-realm
      client:
        provider:
          my-keycloak-provider:
            issuer-uri: http://localhost:8070/realms/macros-realm
        registration:
          keycloak-spring-gateway-client:
            provider: my-keycloak-provider
            scope: openid
            client-id: macros-gateway-client
            client-secret: GA2GS6zMfYHoYltpOSoOMcgQpBCiaAVo
            authorization-grant-type: authorization_code
  cloud:
    gateway:
      routes:
        - id: dish-macros-calculation-server
          uri: lb://DISH-MACROS-CALCULATION-SERVER
          predicates:
            - Path=/calculate-dish/**
        - id: dish-server
          uri: lb://DISH-SERVER
          predicates:
            - Path=/dish/**
        - id: user-server
          uri: lb://USER-SERVER
          predicates:
            - Path=/users/**
        - id: person-macros-calculation-server
          uri: lb://PERSON-MACROS-CALCULATION-SERVER
          predicates:
            - Path=/calculate-person/**
        - id: food-server
          uri: lb://FOOD-SERVER
          predicates:
            - Path=/food/**
        - id: client-aim-server
          uri: lb://CLIENT-AIM-SERVER
          predicates:
            - Path=/monthly-aim/**
        - id: daily-diet-server
          uri: lb://DAILY-DIET-SERVER
          predicates:
            - Path=/daily-diet/**
