server:
  port: 8090

eureka:
  client:
    server-url:
      default-zone: http://localhost:8761/eureka

logstash:
  host: localhost

spring:
  application:
    name: user-server
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8070/realms/macros-realm/protocol/openid-connect/certs
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: password
      database: user-db
      port: 27017
      host: localhost
      auto-index-creation: true
